name: Rust

on:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-12-26
          target: x86_64-unknown-uefi
          components: rustfmt
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true
      - name: Check fmt
        run: cargo fmt --check
      - name: Build
        run: ./.github/workflows/CI-Build.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: valthrun-uefi-mapper
          path: |
            target/x86_64-unknown-uefi/release/valthrun-uefi.efi
            target/x86_64-unknown-uefi/release/valthrun_uefi.pdb
      - name: Build ISO
        run: ./scripts/Create-ISO.ps1 -Bootloader target/x86_64-unknown-uefi/release/valthrun-uefi.efi -Destination ./valthrun-bootloader.iso
      - uses: actions/upload-artifact@v4
        with:
          name: valthrun-bootloader
          path: valthrun-bootloader.iso
