name: Rust

on:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-12-26
          target: x86_64-unknown-uefi
          override: true
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true
      - name: Check fmt
        run: rustup component add rustfmt && cargo fmt --check
      - name: Build
        run: ./.github/workflows/CI-Build.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: valthrun-uefi-mapper
          path: |
            target/x86_64-unknown-uefi/release/valthrun-uefi.efi
            target/x86_64-unknown-uefi/release/valthrun_uefi.pdb
